- name: update package
  apt:
      name: "*"
      state: latest

- name: Install required system packages
  apt:
      name: "{{item}}"
      state: latest
      update_cache: yes
  with_items :
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools

- name: Add Docker GPG apt Key
  apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

- name: Verify that we have the key with the fingerprint
  apt_key:
        id: 0EBFCD88
        state: present

- name: Add Docker Repository
  apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} edge"
        state: present

- name: update package
  apt:
      name: "*"
      state: latest

- name: Install Docker
  package:
    name: Install Ububntu Docker
          - "docker-ce={{version}}"
          - "docker-ce-cli={{version}}"
          - containerd.io
    state: present
  become: yes
  notify: 
  - Restart docker

- name: Add ubuntu user to docker group
  user:
    name: "{{ item }}"
    group: docker
  with_items: "{{ debain_users }}"

- name: install docker-py
  pip:
          name: docker-py

- name: docker ngnix install
  docker_container:
          name: nginx
          image: nginx
          ports:
                 - "80:80"
          volumes:
                 - "/var/www/ngnix:/etc/ngnix:rw"
