- name: opsschool playbook ubuntu
  hosts: ubuntu
  remote_user: ubuntu
  become: yes
  roles:
      - docker
  vars_prompt:
  - name: version
    prompt: "What is docker version you want to install? The default will be:"
    private: no
    default: "5:18.09.0~3-0~ubuntu-bionic"
  

- name: opsschool playbook redhat
  hosts: redhat
  remote_user: ec2-user
  become: yes
  roles:
      - docker
  vars_prompt:
  - name: version
    prompt: "What is docker version you want to install? The default will be:"
    private: no
    default: "3:19.03.13-3.el8"